# Generated by Django 4.2.4 on 2023-08-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveSmallIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='buyer', max_length=100)),
                ('admin_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveSmallIntegerField()),
                ('product_desc', models.TextField()),
                ('product_image', models.ImageField(default='', upload_to='product_image/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productmanager')),
            ],
        ),
    ]
